# Generated by Django 4.1.2 on 2022-12-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_user',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='git_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на github'),
        ),
    ]
