# Generated by Django 4.1.2 on 2022-12-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_birth_date_profile_about_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_see_users', 'Может просматривать пользователей')], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
