# Generated by Django 4.1.2 on 2022-12-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_doings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doings',
            options={},
        ),
    ]
