# Generated by Django 4.1.2 on 2022-12-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_doings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('can_add_users', 'может добавлять участников'), ('can_delete_users', 'может удалять участников')]},
        ),
    ]
